name: rpmbuild

on:
  pull_request:
  workflow_dispatch:

jobs:
  rpmbuild:
    permissions:
      contents: read
    name: "rpmbuild"

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Fedora latest"
            image: "registry.fedoraproject.org/fedora:latest"
          - name: "Fedora Rawhide"
            image: "registry.fedoraproject.org/fedora:rawhide"

    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    steps:
      - name: "Install required packages"
        run: |
          dnf --setopt install_weak_deps=False install -y \
            git make rpm-build dnf5 cmake gcc gcc-c++ libdnf5-devel dnf5-devel gtest-devel jsoncpp-devel

      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Adding repository directory to the temporary git global config as a safe directory (again)"
        run: |
          git config --global --add safe.directory /__w/rhsm-dnf5-plugins/rhsm-dnf5-plugins

      - name: "Build srpm"
        run: |
          make srpm

      - name: "Build rpm"
        run: |
          make rpm
